server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.164.35:3306/online_learning_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: remote
    password: StrongPassword123!

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      spm5:
        olp:
          mapper: debug
          service: info
          controller: info

jwt:
  # JWT签名加密秘钥
  secret-key: online_learning_platform_secret_key_with_at_least_64_characters_for_HS512_algorithm!
  # JWT过期时间(毫秒)
  ttl: 86400000
  # 前端传递的令牌名称
  token-name: token